version: '3.8'
services:
  pdm_hello_world:
    container_name: pdm_hello_world
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: >
      sh -c "pdm run python -m unittest &&
             pdm run hello.py"
    image: "pdm_hello_world:1.0.0"
